<?php

namespace AppBundle\Repository;

/**
 * Email
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Email extends \Doctrine\ORM\EntityRepository
{

    public function getLastestEmails()
    {
        return
            $this->createQueryBuilder('e')
                ->orderBy('e.id', 'DESC')
                ->setMaxResults(10)
                ->getQuery()
                ->getResult();
    }
}
